#define BG_COLOR 						3
#define TEXT_TITLE_COLOR				2
#define TEXT_COLOR 						1
#define BG_BUTTON_SELECT 				1
#define BG_BUTTON_DEFAULT 				9
#define TEXT_BUTTON_SELECT 				15
#define TEXT_BUTTON_DEFAULT				 0
#define BORDER_COLOR 					0
#define TIPS 							6
#define LINE							3
#define TEXT_EDIITEXT_TITLE_COLOR 		0
#define TEXT_EDIITEXT_HINT_COLOR 		8
#define TEXT_EDITTEXT_COLOR				0
#define BG_EDITTEXT_COLOR				7

#define MAX_DAU_SACH 			     	300
#define MAX_DOC_GIA 					200
#define QUEUE_CAPACITY 					200
#define START_ID_DG						1e4
#define END_ID_DG 						1e5
const int ENTER = 13;
const int BACKSPACE = 8;
const int SPACE = 32;
 
enum Type {NHAP_SACH,XOA_SACH, THEM_SACH, HIEU_CHINH_SACH,NONE};
enum Window {THEM_DAU_SACH,DANH_SACH_SACH, HIEU_CHINH_DAU_SACH, DANH_MUC_SACH, DS_DOC_GIA, THEM_DOC_GIA, DOC_GIA_QUA_HAN,HIEU_CHINH_DOC_GIA, XOA_DOC_GIA, MUON_SACH,TT_DOC_GIA, TRA_SACH, TOP_TEN};
enum SubWindow { XOA_ISBN,HIEU_CHINH,MT_NHAP_SACH, MT_KHOA,DMS_MT, XAC_NHAN_TRA_SACH, XAC_NHAN_LAM_MAT_SACH};
enum ScanType{ ONLY_NUMBER, ONLY_NUMBER_GREATER_0, LIMIT_CHARACTER, ONLY_TEXT, SPACE_TEXT, TEXT_NUMBER, FIND_DS, FIND_DSMT,DATE_TIME, ISBN, MASACH};
